name: vpn_client
description: A minimal VLESS VPN client with modern Mullvad-style design.
version: 1.2.6+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  path: ^1.8.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/servers.json
    - sing-box/config_template.json
