name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Download sing-box binary
        shell: bash
        run: |
          mkdir -p vpn_client/sing-box
          curl -Lo vpn_client/sing-box/sing-box.exe https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-windows-amd64.exe

      - name: Install dependencies
        run: flutter pub get
        working-directory: vpn_client

      - name: Ensure Windows support
        run: flutter create --platforms=windows .
        working-directory: vpn_client

      - name: Build Flutter app (Windows)
        run: flutter build windows --release
        working-directory: vpn_client

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: vpn_client/build/windows/runner/Release
