name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
      - run: flutter create . --platforms=windows
        working-directory: vpn_client

    steps:
      - uses: actions/checkout@v3

      - name: Download sing-box binary
        run: |
          mkdir sing-box
          curl -Lo sing-box/sing-box.exe https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-windows-amd64.exe

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get
        working-directory: vpn_client

      - name: Build app
        run: flutter build windows --release
        working-directory: vpn_client

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: vpn_client/build/windows/runner/Release
