name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Download latest sing-box binary
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | cut -d '"' -f4)
          FILE="sing-box-${VERSION#v}-windows-amd64.exe"
          URL="https://github.com/SagerNet/sing-box/releases/download/${VERSION}/${FILE}"
          mkdir -p vpn_client/sing-box
          echo "Downloading $URL..."
          curl -L "$URL" -o "vpn_client/sing-box/sing-box.exe"

      - name: Download Wintun DLL
        shell: bash
        run: |
          echo "Downloading Wintun DLL..."
          curl -L "https://www.wintun.net/builds/wintun-0.14.1.zip" -o wintun.zip
          unzip -q wintun.zip
          mkdir -p vpn_client/sing-box
          cp wintun/bin/amd64/wintun.dll vpn_client/sing-box/wintun.dll
          rm -rf wintun.zip wintun

      - name: Install dependencies
        run: flutter pub get
        working-directory: vpn_client

      - name: Add Windows platform
        run: flutter create --platforms=windows .
        working-directory: vpn_client

      - name: Build Flutter app (Windows)
        run: flutter build windows --release
        working-directory: vpn_client

      - name: Copy dependencies to release folder
        shell: cmd
        working-directory: vpn_client
        run: |
          copy sing-box\sing-box.exe build\windows\runner\Release\sing-box.exe
          if exist sing-box\wintun.dll copy sing-box\wintun.dll build\windows\runner\Release\wintun.dll

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpn-client-windows
          path: vpn_client/build/windows/runner/Release
