name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd vpn_client
        flutter pub get
    
    - name: Analyze code
      run: |
        cd vpn_client
        flutter analyze
    
    - name: Run tests
      run: |
        cd vpn_client
        flutter test

    # Временно отключена проверка форматирования
    # - name: Check formatting
    #   run: |
    #     cd vpn_client
    #     flutter format --set-exit-if-changed .

  build:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd vpn_client
        flutter pub get
    
    - name: Build Windows app
      run: |
        cd vpn_client
        flutter build windows --release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: vpn_client/build/windows/runner/Release/
        
    - name: Create build info
      run: |
        echo "Build completed at $(Get-Date)" > build-info.txt
        echo "Commit: ${{ github.sha }}" >> build-info.txt
        echo "Branch: ${{ github.ref_name }}" >> build-info.txt
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: build-info.txt
