name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Download latest sing-box binary
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | cut -d '"' -f4)
          FILE="sing-box-${VERSION#v}-windows-amd64.exe"
          URL="https://github.com/SagerNet/sing-box/releases/download/${VERSION}/${FILE}"
          mkdir -p vpn_client/sing-box
          echo "Downloading $URL..."
          curl -L "$URL" -o "vpn_client/sing-box/sing-box.exe"

      - name: Install dependencies
        run: flutter pub get
        working-directory: vpn_client

      - name: Add Windows platform
        run: flutter create --platforms=windows .
        working-directory: vpn_client

      - name: Build Flutter app (Windows)
        run: flutter build windows --release
        working-directory: vpn_client

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpn-client-windows
          path: vpn_client/build/windows/runner/Release
